"use strict";
require("./storage.test.js");
require("./scoring.test.js");
require("./usage.test.js");
require("./ui.test.js");
require("./parent-area.test.js");
require("./arithmetic-rules.test.js");
require("./memory-rules.test.js");
require("./game-dom.test.js");
require("./spelling-rules.test.js");
